### ISSUE TITLE
Error on start up from Cooking module

### ISSUE THREAD

**Issue by MilkmanWes** [tullamods/Wildpants#10]
Date: 2017-09-25 19:14:55
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\Combuctor_Cuisine\Combuctor_Cuisine.lua line 9:
   attempt to call global 'GetAuctionItemClasses' (a nil value)
Debug:
   ...rface\AddOns\Combuctor_Cuisine\Combuctor_Cuisine.lua:9: in main chunk
Locals:
CombuctorSet = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Unregister = <function> defined @Interface\AddOns\Combuctor\legacy.lua:39
 Register = <function> defined @Interface\AddOns\Combuctor\legacy.lua:24
 Enable = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 defaultModuleLibraries = <table> {
 }
 baseName = "Combuctor"
 RegisterSubSet = <function> defined @Interface\AddOns\Combuctor\legacy.lua:30
 SetEnabledState = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Get = <function> defined @Interface\AddOns\Combuctor\legacy.lua:43
 enabledState = true
 GetParentSets = <function> defined @Interface\AddOns\Combuctor\legacy.lua:51
 GetChildSets = <function> defined @Interface\AddOns\Combuctor\legacy.lua:55
 moduleName = "Sets"
 GetName = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 IterateModules = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 name = "Combuctor_Sets"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 IsEnabled = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 DisableModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
}
IconPathName = "Interface/Icons/Inv_misc_food_15"
ProfessionName = 12
(*temporary) = <function> defined =[C]:-1
(*temporary) = 7
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Arh, v1.6.4
  ArtifactPowerUser, v3.1
  ArtifactTab, v2.3.2
  AskMrRobot, v52
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  CollectMe, v2.9.4
  Combuctor, v7.3
  CombuctorCuisine, v6.2.0
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  LibExtraTip, v5.12.DEV.423(/embedded)
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=758)

**Comment by Jaliborc** [comment]
I am not the developer of that plugin. It is out of date
