### ISSUE TITLE
Bagnon 8.0.0b: Missing Void Storage Folder?

### ISSUE THREAD

**Issue by Lunaeria** [tullamods/Wildpants#13]
I updated the addon for the pre-patch, and everything's working perfectly, but when I went to go check my Void Storage, I realised Bagnon wasn't working for it. I hunted through the settings, couldn't find a toggle for it, then I looked in my addon list and noticed the module was missing, so I checked my actual addon folder and... the Bagnon_VoidStorage folder is missing completely.

I downloaded some older versions of the addon, to ensure I wasn't just imagining things, but the folder is present in previous releases (specifically 7.3.2 and 7.3.11, as though were the two I checked), so I'm a little confused. I can't find any recent references to the Void Storage module in the changelog, so I'm not sure if it was deliberately removed or not.

I copied over the Bagnon_VoidStorage module from the 7.3.2 release of the addon and so far it seems to be working okay, with no lua errors in sight.

**Comment by Tuller** [comment]
I turned it off since I wasn't able to verify it for the 8.0.0 release.

**Comment by Lunaeria** [comment]
Ah, okay. Fair enough! The 7.3.2 version seems to be working okay for now, at least. I don't use my void storage too often anyways... Thank you for the response!
