### ISSUE TITLE
Converge all code into single repo

### ISSUE THREAD

**Issue by Jaliborc** [tullamods/Wildpants#25]
My experience having all the code in the main folder with PetTracker, and having submodules be only a .toc file has been fantastic.

Need to do the same with wildpants, its way to many repos to manage and wasted time.

**Comment by Tuller** [comment]
Do you mean more merging wildpants into bagnon, or something else?

**Comment by Jaliborc** [comment]
Something else. Having all the code for Bagnon_Config, Bagnon_GuildBank and Bagnon_VoidStorage in Bagnon. Having the code for Combuctor_Config in Combuctor (Wildpants_Config would move into Wildpants.) The other become just .toc files that load the corresponding LOD .xml .lua files. 

Essentially the same thing, files will just move around and repos will be easier to manage. Has no effect on performance, memory usage or how things are coded. PetTracker does that already, and was originally split as well.

**Comment by Tuller** [comment]
That's more what I was thinking. Dominos is structured like that now, as is tullaRange.

**Comment by Jaliborc** [comment]
Cool, nice you like it too. Wildpants is still needed to share code with Combuctor, otherwise it would be twice the work.

Mind if I do that to OmniCC as well, while I'm at it?

**Comment by Tuller** [comment]
You can, I was thinking about doing that over the weekend
