### ISSUE TITLE
missing panel string locales on config.

### ISSUE THREAD

**Issue by adavak** [tullamods/Wildpants#27]
Bagnon\common\Wildpants\config:

	self:CreateHeader('Items', 'GameFontHighlight', true)
to
	self:CreateHeader(L.Items, 'GameFontHighlight', true)

and

	self:CreateHeader('Slots', 'GameFontHighlight', true).top = 15
to
	self:CreateHeader(L.Slots, 'GameFontHighlight', true).top = 15

and add string to localization. thanks.

**Comment by Jaliborc** [comment]
How... did I miss that?! My bad, fixed internally.
