### ISSUE TITLE
wow classic quiver sorting

### ISSUE THREAD

**Issue by Lmeks** [tullamods/Wildpants#41]
Hey there, I use last version of Bagnon on WoW classic and Bagnon\common\Wildpants\api\sorting.lua seems to ignore whether bag is a quiver or not.
So I almost always have to press sorting button several times.
Wheres the problem? Should i contact bagnon developer(s)?
Thanks

**Comment by Lmeks** [comment]
I've reinstalled my bagnon and it seems it doesnt ignore quivers but it takes several clicks to sort items out and i sometimes end up with an item on my cursor.
Here's the video of the issue. Sometimes i get "item doesnt go into that container message".
https://youtu.be/2KuB92vRtmw

**Comment by Jaliborc** [comment]
should now be impossible to get an item stuck to the cursor
