### ISSUE TITLE
Items get stuck to the cursor while sorting

### ISSUE THREAD

**Issue by Lmeks** [tullamods/Wildpants#45]
So I've updated and reinstalled Bagnon (classic) and it seems item sorting has better success rate, but items can still stuck to the cursor.
Here's video of an example.
https://youtu.be/Rl-Mv2_oYjE

**Comment by Jaliborc** [comment]
I believe what you are experiencing is due to high server delay.
There is little I can do to further improve it as a mod dev I think. That's why it randomly "works" or not. Depends on the latency at the moment of operations.

**Comment by Lmeks** [comment]
Well the only possible improvement I can see is change of sorting algorythm.
For example:
Step 1. Find all stackable items and make sure there's only one item with less than maximum amount of possble pieces.
Step 2. Build perfect inventory client side.
Step 3. Selectively move items from actual inventory to the 1st possible correct position.
This should descrease burden of client-server communication. Also step 1 is not required.

**Comment by Jaliborc** [comment]
Thats already what it does
