### ISSUE TITLE
Icons broken for Lightforged, HM Tauren and Zandalari

### ISSUE THREAD

**Issue by justinkb** [tullamods/Wildpants#46]
Since the change to using the other method of using the atlas icons, these have been broken.

Per https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/GlueXML/CharacterCreate.lua#L617 you'd need to do some manual tweaking to the race string for those too, not just for the Undead.

```
		local race = owner.race:lower()
		race = race:gsub('highmountaintauren', 'highmountain')
		race = race:gsub('lightforgeddraenei', 'lightforged')
		race = race:gsub('scourge', 'undead')
		race = race:gsub('zandalaritroll', 'zandalari')
```

Not sure about the performance of gsub, but this seems to work fine.

```
		local race = owner.race:lower()
		if race == 'highmountaintauren' then
			race = 'highmountain'
		elseif race == 'lightforgeddraenei' then
			race = 'lightforged'
		elseif race == 'scourge' then
			race = 'undead'
		elseif race == 'zandalaritroll' then
			race = 'zandalari'
		end
```

edit: the above is probably more performant

**Comment by Jaliborc** [comment]
Nice! I guessed something along those lines was happening, but don't have allied races myself to test. Thanks for the help
